version: "3"

services:
  cli:
    container_name: assignment-github-cli
    build: './.docker/cli'
    volumes:
      - ./:/var/www/arena
      
  webserver:
    image: nginx:latest
    container_name: assignment-github-ngnix
    restart: 'always'
    ports:
      - "8080:80"
    links:
      - php
      - mysql
    volumes:
      - ./:/var/www/assignment-github
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
        default:
            ipv4_address: 182.25.1.3
      
  php:
    build: './.docker/php81'
    container_name: assignment-github-php
    volumes: 
      - ./:/var/www/arena
    networks:
        default:
            ipv4_address: 182.25.1.4
            
  mysql:
    image: mysql:5.7.22
    container_name: assignment-github-mysql
    tty: true
    ports:
      - "3366:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    networks:
        default:
            ipv4_address: 182.25.1.6
            
  phpmyadmin-assignment-github:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin-assignment-github'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '8181:80'
    networks:
        default:
            ipv4_address: 182.25.1.8
      
networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 182.25.0.0/16
